### ISSUE TITLE
geometry_msgs/TwistStamped is being converted to geometry_msgs/Twist

### ISSUE THREAD

**Issue by KKonaOG** [StefanFabian/ros_babel_fish#12] opened 2023-07-03 04:26 UTC
Hi all!

I'm attempting to use ros_babel_fish to repackage ROS data, however, geometry_msgs/TwistStamped seems to be converted to geometry_msgs/Twist by the package resulting in an exception when transforming the message.

Any thoughts on how to resolve this?

Thanks,
KKonaOG

**Comment by KKonaOG** [comment] 2023-07-03 04:59
This is my current work around which I am not entirely sure if its ideal:
`
    ros_babel_fish::BabelFishMessage::Ptr msg_copy(new ros_babel_fish::BabelFishMessage(*msg));

    TranslatedMessage::Ptr translated_msg;
    std::shared_ptr<nt::NetworkTable> NT_table = NT_inst.GetTable(topic_name);
    
    try {
        translated_msg = fish->translateMessage(msg_copy);
    } catch (ros_babel_fish::BabelFishException) {
        if (msg->dataType() == "geometry_msgs/Twist") {
            msg_copy->morph(fish->descriptionProvider()->getMessageDescription("geometry_msgs/TwistStamped"));
            translated_msg = fish->translateMessage(msg_copy);
        } else {
            exit(EXIT_FAILURE);
        }
    }`

It does seem to understand the definition it just isn't parsing it to the correct type when coming into the callback.

**Comment by StefanFabian** [comment] 2023-07-04 15:38
This is a very unusual behavior. What does `rostopic info` say about the topic?
The message type is set automatically from the information ROS obtains when making the connection (see [here](https://github.com/StefanFabian/ros_babel_fish/blob/kinetic/ros_babel_fish/include/ros_babel_fish/babel_fish_message.h#L231)), hence, I find it more likely that the issue is somewhere in your setup and to exclude that possibility I would need more information.
Can you give a minimum working example to reproduce the issue?

**Comment by StefanFabian** [comment] 2023-12-27 11:54
Closing since no investigation is possible without further information.

**Closed as completed by StefanFabian** 2023-12-27 11:54 UTC
